#thymeleaf模板
spring:
  thymeleaf:
    cache: true
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML5
  encoding: UTF-8
  servlet:
    content-type: text/html
#数据连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.77:3306/tyzn?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: tyzn
    password: tyzn

  # mybatis 配置
  mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml